### ISSUE TITLE
Make "Personality Values" display separately

### ISSUE THREAD

**Issue by Inf1nitius** [Yuuki2628/ASPR#2]
![image](https://user-images.githubusercontent.com/69798995/175768625-5b8e78ce-6110-4b73-bcba-443a5de61664.png)

Instead of having "Personality Values" as a single row, separate into "Personality Attack Resistance" and "Personality Persuasion Resistance" respectively (Suggested names are not final), since the current display may be confusing to new users.

| Suggested: | |
|--|--|
| Personality Attack Resistance:     | 1.15 |
| Personality Persuasion Resistance: | 1 |

i mean, come on yuuki, its just a simple qol thing just do it

**Comment by Kronweber** [comment]
not even a qol improvement, it just adds a new row

I'll do it when exams are over if I remember, if I don't by next month then you are allowed to spam me

**Comment by Inf1nitius** [comment]
well... we are halfway into july 👀
by next month did you mean july or after 1 month :goblinfire:

also its qol cos it makes it look better
and easier to use
